/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    formacoes: Formacoe;
    eventos: Evento;
    livros: Livro;
    blog: Blog;
    mentores: Mentore;
    testimonials: Testimonial;
    faqs: Faq;
    pages: Page;
    media: Media;
    forms: Form;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    formacoes: FormacoesSelect<false> | FormacoesSelect<true>;
    eventos: EventosSelect<false> | EventosSelect<true>;
    livros: LivrosSelect<false> | LivrosSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    mentores: MentoresSelect<false> | MentoresSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'editor' | 'author';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formacoes".
 */
export interface Formacoe {
  id: string;
  title: string;
  /**
   * URL amigável (ex: educador-financeiro)
   */
  slug: string;
  status: 'draft' | 'published' | 'archived';
  /**
   * Código hexadecimal (ex: #FFD700)
   */
  accentColor?: string | null;
  /**
   * Escolha o template de design para esta formação. Cada template mantém o design original da página.
   */
  template?:
    | (
        | 'default'
        | 'empreendedor-inteligente'
        | 'lcf-mentoring-pro'
        | 'mentoria-individual'
        | 'mentoria-investimentos'
        | 'metodo-tf'
        | 'rota-mind'
        | 'custom'
      )
    | null;
  /**
   * Selecione o formulário que será exibido na seção de inscrição. Crie formulários em "Forms" primeiro.
   */
  form?: (string | null) | Form;
  hero?: {
    badge?: string | null;
    title?: string | null;
    subtitle?: string | null;
    description?:
      | {
          [k: string]: unknown;
        }[]
      | null;
    backgroundImage?: (string | null) | Media;
    ctaText?: string | null;
    ctaLink?: string | null;
  };
  challenges?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * Nome do ícone Lucide (ex: Trophy, Target)
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  learnings?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  modules?:
    | {
        title?: string | null;
        description?: string | null;
        topics?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bonuses?:
    | {
        title?: string | null;
        description?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  video?: {
    type?: ('youtube' | 'upload') | null;
    youtubeId?: string | null;
    file?: (string | null) | Media;
  };
  pricing?: {
    price?: number | null;
    installments?: number | null;
    installmentValue?: number | null;
    link?: string | null;
  };
  guarantee?: {
    days?: number | null;
    description?:
      | {
          [k: string]: unknown;
        }[]
      | null;
  };
  faqs?: (string | Faq)[] | null;
  testimonials?: (string | Testimonial)[] | null;
  mentors?: (string | Mentore)[] | null;
  certification?: {
    hasCertification?: boolean | null;
    certificationText?:
      | {
          [k: string]: unknown;
        }[]
      | null;
    certificationImage?: (string | null) | Media;
  };
  professionalLicense?: {
    enabled?: boolean | null;
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    transformationTitle?: string | null;
    transformations?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    benefitsTitle?: string | null;
    benefits?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    shieldMessage?: string | null;
    shieldDescription?: string | null;
    ctaText?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  name: string;
  /**
   * Identificador único do formulário (ex: contato, newsletter). Será gerado automaticamente se não preenchido.
   */
  slug: string;
  /**
   * Descrição do propósito do formulário
   */
  description?: string | null;
  fields: {
    /**
     * Nome técnico do campo (ex: email, nome)
     */
    name: string;
    /**
     * Texto exibido ao usuário
     */
    label: string;
    type: 'text' | 'email' | 'tel' | 'number' | 'textarea' | 'select' | 'checkbox' | 'radio' | 'date' | 'file';
    required?: boolean | null;
    placeholder?: string | null;
    options?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    validation?: {
      minLength?: number | null;
      maxLength?: number | null;
      /**
       * Expressão regular para validação
       */
      pattern?: string | null;
    };
    id?: string | null;
  }[];
  settings?: {
    submitText?: string | null;
    successMessage?: string | null;
    /**
     * URL para redirecionar após envio (opcional)
     */
    redirectUrl?: string | null;
    emailNotifications?: {
      enabled?: boolean | null;
      to?: string | null;
      subject?: string | null;
    };
    webhook?: {
      /**
       * Enviar dados do formulário para uma URL externa
       */
      enabled?: boolean | null;
      /**
       * URL completa do webhook (ex: https://api.exemplo.com/webhook)
       */
      url?: string | null;
      method?: ('POST' | 'PUT' | 'PATCH') | null;
      /**
       * Headers adicionais para enviar com o webhook (ex: Authorization)
       */
      headers?:
        | {
            key: string;
            value: string;
            id?: string | null;
          }[]
        | null;
      /**
       * Tempo máximo de espera pela resposta do webhook
       */
      timeout?: number | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: {
    [k: string]: unknown;
  }[];
  category?: ('formacao' | 'evento' | 'livro' | 'pagamento' | 'certificacao' | 'geral') | null;
  /**
   * Ordem de exibição (menor = primeiro)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  role?: string | null;
  company?: string | null;
  photo?: (string | null) | Media;
  testimonial: string;
  /**
   * De 1 a 5 estrelas
   */
  rating?: number | null;
  /**
   * YouTube URL ou ID
   */
  videoUrl?: string | null;
  featured?: boolean | null;
  category?: ('formacao' | 'evento' | 'livro' | 'geral') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentores".
 */
export interface Mentore {
  id: string;
  name: string;
  slug: string;
  role?: string | null;
  photo?: (string | null) | Media;
  bio?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  shortBio?: string | null;
  achievements?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    instagram?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    facebook?: string | null;
  };
  featured?: boolean | null;
  /**
   * Ordem de exibição (menor = primeiro)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos".
 */
export interface Evento {
  id: string;
  title: string;
  slug: string;
  status: 'draft' | 'published' | 'closed';
  accentColor?: string | null;
  template?:
    | (
        | 'default'
        | 'crencas-da-riqueza'
        | 'energia-do-dinheiro'
        | 'segredos-da-mente-milionaria'
        | 'escalador-de-negocios'
        | 'mentor-milionario'
      )
    | null;
  date: string;
  endDate?: string | null;
  /**
   * Ex: 7 horas intensivas
   */
  duration?: string | null;
  location?: {
    type?: ('presencial' | 'online' | 'hybrid') | null;
    venue?: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
  };
  hero?: {
    badge?: string | null;
    title?: string | null;
    subtitle?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  countdown?: {
    enabled?: boolean | null;
    targetDate?: string | null;
  };
  highlights?:
    | {
        title?: string | null;
        description?: string | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  learnings?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  challenges?:
    | {
        question?: string | null;
        answer?: string | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  intelligenceTypes?:
    | {
        title?: string | null;
        description?: string | null;
        icon?: string | null;
        benefits?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  schedule?:
    | {
        time?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  tickets?:
    | {
        name?: string | null;
        type?: ('free' | 'paid' | 'vip') | null;
        price?: number | null;
        originalPrice?: number | null;
        description?: string | null;
        benefits?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        link?: string | null;
        available?: boolean | null;
        id?: string | null;
      }[]
    | null;
  video?: {
    type?: ('youtube' | 'upload') | null;
    youtubeId?: string | null;
    file?: (string | null) | Media;
  };
  mentors?: (string | Mentore)[] | null;
  faqs?: (string | Faq)[] | null;
  testimonials?: (string | Testimonial)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "livros".
 */
export interface Livro {
  id: string;
  title: string;
  slug: string;
  author?: string | null;
  subtitle?: string | null;
  description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  coverImage?: (string | null) | Media;
  price?: number | null;
  amazonLink?: string | null;
  purchaseLink?: string | null;
  pages?: number | null;
  publishDate?: string | null;
  isbn?: string | null;
  highlights?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  whatYouWillLearn?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  testimonials?: (string | Testimonial)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  title: string;
  /**
   * URL amigável (ex: meu-post)
   */
  slug: string;
  status: 'draft' | 'published' | 'archived';
  /**
   * Breve descrição do post (aparece na listagem)
   */
  excerpt: string;
  content: {
    [k: string]: unknown;
  }[];
  coverImage?: (string | null) | Media;
  author?: string | null;
  category: 'Mentalidade' | 'Coragem' | 'Inteligência Emocional' | 'Decisões Financeiras';
  publishedAt: string;
  /**
   * Tempo estimado de leitura em minutos
   */
  readingTime?: number | null;
  seo?: {
    /**
     * Título para SEO (deixe vazio para usar o título do post)
     */
    title?: string | null;
    /**
     * Meta description para SEO
     */
    description?: string | null;
    /**
     * Palavras-chave separadas por vírgula
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL da página (ex: politica-privacidade)
   */
  slug: string;
  status: 'draft' | 'published';
  layout?: ('default' | 'hero-image' | 'hero-red' | 'form' | 'custom') | null;
  hero?: {
    title?: string | null;
    subtitle?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  content?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  sections?:
    | {
        type?: ('text' | 'image' | 'video' | 'form' | 'cta' | 'grid') | null;
        content?:
          | {
              [k: string]: unknown;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  form?: {
    formId?: string | null;
    submitText?: string | null;
    successMessage?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'formacoes';
        value: string | Formacoe;
      } | null)
    | ({
        relationTo: 'eventos';
        value: string | Evento;
      } | null)
    | ({
        relationTo: 'livros';
        value: string | Livro;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'mentores';
        value: string | Mentore;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formacoes_select".
 */
export interface FormacoesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  accentColor?: T;
  template?: T;
  form?: T;
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        backgroundImage?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  challenges?:
    | T
    | {
        text?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  learnings?:
    | T
    | {
        text?: T;
        id?: T;
      };
  modules?:
    | T
    | {
        title?: T;
        description?: T;
        topics?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  bonuses?:
    | T
    | {
        title?: T;
        description?: T;
        value?: T;
        id?: T;
      };
  video?:
    | T
    | {
        type?: T;
        youtubeId?: T;
        file?: T;
      };
  pricing?:
    | T
    | {
        price?: T;
        installments?: T;
        installmentValue?: T;
        link?: T;
      };
  guarantee?:
    | T
    | {
        days?: T;
        description?: T;
      };
  faqs?: T;
  testimonials?: T;
  mentors?: T;
  certification?:
    | T
    | {
        hasCertification?: T;
        certificationText?: T;
        certificationImage?: T;
      };
  professionalLicense?:
    | T
    | {
        enabled?: T;
        badge?: T;
        title?: T;
        description?: T;
        transformationTitle?: T;
        transformations?:
          | T
          | {
              text?: T;
              id?: T;
            };
        benefitsTitle?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
        shieldMessage?: T;
        shieldDescription?: T;
        ctaText?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos_select".
 */
export interface EventosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  accentColor?: T;
  template?: T;
  date?: T;
  endDate?: T;
  duration?: T;
  location?:
    | T
    | {
        type?: T;
        venue?: T;
        address?: T;
        city?: T;
        state?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
      };
  countdown?:
    | T
    | {
        enabled?: T;
        targetDate?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  learnings?:
    | T
    | {
        text?: T;
        id?: T;
      };
  challenges?:
    | T
    | {
        question?: T;
        answer?: T;
        icon?: T;
        id?: T;
      };
  intelligenceTypes?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  schedule?:
    | T
    | {
        time?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  tickets?:
    | T
    | {
        name?: T;
        type?: T;
        price?: T;
        originalPrice?: T;
        description?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
        link?: T;
        available?: T;
        id?: T;
      };
  video?:
    | T
    | {
        type?: T;
        youtubeId?: T;
        file?: T;
      };
  mentors?: T;
  faqs?: T;
  testimonials?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "livros_select".
 */
export interface LivrosSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  subtitle?: T;
  description?: T;
  coverImage?: T;
  price?: T;
  amazonLink?: T;
  purchaseLink?: T;
  pages?: T;
  publishDate?: T;
  isbn?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whatYouWillLearn?:
    | T
    | {
        text?: T;
        id?: T;
      };
  testimonials?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  author?: T;
  category?: T;
  publishedAt?: T;
  readingTime?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentores_select".
 */
export interface MentoresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  photo?: T;
  bio?: T;
  shortBio?: T;
  achievements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        linkedin?: T;
        youtube?: T;
        facebook?: T;
      };
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  photo?: T;
  testimonial?: T;
  rating?: T;
  videoUrl?: T;
  featured?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  layout?: T;
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
      };
  content?: T;
  sections?:
    | T
    | {
        type?: T;
        content?: T;
        id?: T;
      };
  form?:
    | T
    | {
        formId?: T;
        submitText?: T;
        successMessage?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  fields?:
    | T
    | {
        name?: T;
        label?: T;
        type?: T;
        required?: T;
        placeholder?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        validation?:
          | T
          | {
              minLength?: T;
              maxLength?: T;
              pattern?: T;
            };
        id?: T;
      };
  settings?:
    | T
    | {
        submitText?: T;
        successMessage?: T;
        redirectUrl?: T;
        emailNotifications?:
          | T
          | {
              enabled?: T;
              to?: T;
              subject?: T;
            };
        webhook?:
          | T
          | {
              enabled?: T;
              url?: T;
              method?: T;
              headers?:
                | T
                | {
                    key?: T;
                    value?: T;
                    id?: T;
                  };
              timeout?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}