export const formationBySlugQuery = `*[_type == "formationPage" && slug.current == $slug] | order(_updatedAt desc)[0]{
  _id,
  title,
  slug,
  hero{ title, subtitle, description, ctaText, ctaLink, backgroundImage{asset->{url}} },
  controls{ showBenefits, showMainContent, showHighlights, showBonuses, showPricing, showTestimonials, showFaq },
  mainContent{ badge, title, description, items[]{ title, description, benefits[] } },
  benefits{ badge, title, description, items[]{ title, description } },
  highlights{ badge, title, items[]{ title, description, image{asset->{url}} } },
  bonuses{ badge, title, items[]{ value, title, description } },
  pricing{ badge, title, description, tickets[]{ name, price, description, features[], highlighted, ctaText, ctaLink } },
  testimonials{ badge, title, description, items[]{ name, role, quote, rating } },
  faq{ badge, title, items[]{ question, answer } },
  finalCta{ title, description, buttonText, buttonLink },
  mecSection{ heading, description, image{asset->{url}}, points },
  aboutSection{ badge, heading, paragraphs, image{asset->{url}}, ctaText, ctaLink },
  licenseSection{ transformationsTitle, transformations, benefitsTitle, benefits, statement },
  exclusiveMaterials{ badge, heading, description, chips, videoSrc, videoPoster{asset->{url}}, ctaText },
  features{ badge, title, items[]{ icon, title, description } },
  trainerSection{ badge, title, description, courses[]{ title, description, image{asset->{url}} } },
  mentorSection{ badge, title, image{asset->{url}}, paragraphs },
  guarantees{ badge, title, items[]{ title, description } },
  newsletter{ title, description, ctaText },
  challengesSection{ badge, title, description, items[]{ title, desc } },
  valueSection{ badge, title, paragraphs, ctaText, ctaLink },
  learnSection{ badge, title, items[]{ title, desc, icon }, ctaText, ctaLink },
  methodologySection{ badge, title, description, items[]{ title, desc, icon }, ctaText, ctaLink },
  audienceSection{ badge, title, intro, bullets[]{ title, desc }, ctaText, ctaLink },
  faqSection{ badge, title, items[]{ question, answer } }
}`


